import { useRoomForm } from "./use-room-form";
import { useRoomsData } from "./use-rooms-data";

export function useRoomsManagement() {
  const data = useRoomsData();
  const form = useRoomForm({
    resources: data.resources,
    purposes: data.purposes,
    setPurposes: data.setPurposes,
    setLoading: data.setLoading,
    setError: data.setError,
    loadRooms: data.loadRooms,
  });

  return {
    rooms: data.rooms,
    purposes: data.purposes,
    resources: data.resources,
    loading: data.loading,
    error: data.error,
    openRoomDialog: form.openRoomDialog,
    openSearchDialog: data.openSearchDialog,
    searchType: data.searchType,
    searchValue: data.searchValue,
    currentPage: data.currentPage,
    itemsPerPage: data.itemsPerPage,
    isAdmin: data.isAdmin,
    isEditMode: form.isEditMode,
    formData: form.formData,
    purposeInput: form.purposeInput,
    selectedPurpose: form.selectedPurpose,
    fixedResourceId: form.fixedResourceId,
    optionalResourceId: form.optionalResourceId,
    fixedResourceQty: form.fixedResourceQty,
    optionalResourceQty: form.optionalResourceQty,
    typeAttributeFields: form.typeAttributeFields,
    setError: data.setError,
    setSearchType: data.setSearchType,
    setSearchValue: data.setSearchValue,
    setPurposeInput: form.setPurposeInput,
    setSelectedPurpose: form.setSelectedPurpose,
    setFixedResourceId: form.setFixedResourceId,
    setOptionalResourceId: form.setOptionalResourceId,
    setFixedResourceQty: form.setFixedResourceQty,
    setOptionalResourceQty: form.setOptionalResourceQty,
    setFormData: form.setFormData,
    openCreateDialog: form.openCreateDialog,
    openEditDialog: form.openEditDialog,
    closeRoomDialog: form.closeRoomDialog,
    setOpenSearchDialog: data.setOpenSearchDialog,
    loadRooms: data.loadRooms,
    handleSaveRoom: form.handleSaveRoom,
    handleDeleteRoom: data.handleDeleteRoom,
    handleAddPurpose: form.handleAddPurpose,
    handleCreatePurpose: form.handleCreatePurpose,
    handleRemovePurpose: form.handleRemovePurpose,
    handleSearch: data.handleSearch,
    addFixedResource: form.addFixedResource,
    addOptionalResource: form.addOptionalResource,
    addTypeAttributeField: form.addTypeAttributeField,
    updateTypeAttributeField: form.updateTypeAttributeField,
    removeTypeAttributeField: form.removeTypeAttributeField,
    removeResourceAssignment: form.removeResourceAssignment,
    getResourceLabel: form.getResourceLabel,
  };
}
