"""calendar_block reservation_id

Revision ID: 4ad6a3385097
Revises: 6ae9bab4cd88
Create Date: 2026-06-01 19:16:41.118778

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad6a3385097'
down_revision: str | Sequence[str] | None = '6ae9bab4cd88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_blocks', sa.Column('reservation_id', sa.Integer(), nullable=True))
    op.create_foreign_key('calendar_blocks_reservation_id_fkey', 'calendar_blocks', 'reservations', ['reservation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calendar_blocks_reservation_id_fkey', 'calendar_blocks', type_='foreignkey')
    op.drop_column('calendar_blocks', 'reservation_id')
    # ### end Alembic commands ###
