"""notifications table

Revision ID: 6ae9bab4cd88
Revises: 58d0521d2147
Create Date: 2026-06-01 18:54:42.571148

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae9bab4cd88'
down_revision: str | Sequence[str] | None = '58d0521d2147'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('RESERVATION_APPROVED', 'RESERVATION_REJECTED', 'SUPPORT_PENDING', 'PENALTY_APPLIED', 'APPEAL_RESOLVED', 'COMPOSITE_REVISION_REQUIRED', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_target_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
