"""first migration

Revision ID: 6dac63b81854
Revises: 
Create Date: 2026-03-14 17:13:16.703058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dac63b81854'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purposes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purposes'))
    )
    op.create_index(op.f('ix_purposes_id'), 'purposes', ['id'], unique=False)
    op.create_index(op.f('ix_purposes_name'), 'purposes', ['name'], unique=True)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('availability_notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_resource_code'), 'resources', ['resource_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('accessibility', sa.Boolean(), nullable=False),
    sa.Column('criticality', sa.String(), nullable=False),
    sa.Column('supervisor_user_id', sa.Integer(), nullable=True),
    sa.Column('type_attributes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_user_id'], ['users.id'], name=op.f('fk_rooms_supervisor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_room_id'), 'rooms', ['room_id'], unique=True)
    op.create_index(op.f('ix_rooms_supervisor_user_id'), 'rooms', ['supervisor_user_id'], unique=False)
    op.create_table('room_purposes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purpose_id'], ['purposes.id'], name=op.f('fk_room_purposes_purpose_id_purposes')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_purposes_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_purposes')),
    sa.UniqueConstraint('room_id', 'purpose_id', name='uq_room_purpose')
    )
    op.create_index(op.f('ix_room_purposes_id'), 'room_purposes', ['id'], unique=False)
    op.create_index(op.f('ix_room_purposes_purpose_id'), 'room_purposes', ['purpose_id'], unique=False)
    op.create_index(op.f('ix_room_purposes_room_id'), 'room_purposes', ['room_id'], unique=False)
    op.create_table('room_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('is_fixed', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_room_resources_resource_id_resources')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_resources_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_resources')),
    sa.UniqueConstraint('room_id', 'resource_id', 'is_fixed', name='uq_room_resource_fixed')
    )
    op.create_index(op.f('ix_room_resources_id'), 'room_resources', ['id'], unique=False)
    op.create_index(op.f('ix_room_resources_resource_id'), 'room_resources', ['resource_id'], unique=False)
    op.create_index(op.f('ix_room_resources_room_id'), 'room_resources', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_resources_room_id'), table_name='room_resources')
    op.drop_index(op.f('ix_room_resources_resource_id'), table_name='room_resources')
    op.drop_index(op.f('ix_room_resources_id'), table_name='room_resources')
    op.drop_table('room_resources')
    op.drop_index(op.f('ix_room_purposes_room_id'), table_name='room_purposes')
    op.drop_index(op.f('ix_room_purposes_purpose_id'), table_name='room_purposes')
    op.drop_index(op.f('ix_room_purposes_id'), table_name='room_purposes')
    op.drop_table('room_purposes')
    op.drop_index(op.f('ix_rooms_supervisor_user_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_room_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resources_resource_code'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_purposes_name'), table_name='purposes')
    op.drop_index(op.f('ix_purposes_id'), table_name='purposes')
    op.drop_table('purposes')
    # ### end Alembic commands ###
