"""environment code

Revision ID: 4c264450bdb1
Revises: 4ad6a3385097
Create Date: 2026-06-01 20:32:34.954558

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c264450bdb1'
down_revision: str | Sequence[str] | None = '4ad6a3385097'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('code', sa.String(length=64), nullable=True))
    op.execute(
        "UPDATE environments SET code = 'AMB-' || LPAD(id::text, 4, '0') "
        "WHERE code IS NULL"
    )
    op.create_unique_constraint('uq_environments_code', 'environments', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_environments_code', 'environments', type_='unique')
    op.drop_column('environments', 'code')
    # ### end Alembic commands ###
