"""ajustando schemas

Revision ID: 9cfd88748d73
Revises: 4256b7d7b301
Create Date: 2026-04-18 17:49:42.770204

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cfd88748d73'
down_revision: str | Sequence[str] | None = '4256b7d7b301'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localizacoes',
    sa.Column('campus', sa.String(length=255), nullable=False),
    sa.Column('predio', sa.String(length=255), nullable=False),
    sa.Column('andar', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localizacoes_id'), 'localizacoes', ['id'], unique=False)
    op.create_table('papeis',
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papeis_codigo'), 'papeis', ['codigo'], unique=True)
    op.create_index(op.f('ix_papeis_id'), 'papeis', ['id'], unique=False)
    op.create_index(op.f('ix_papeis_nome'), 'papeis', ['nome'], unique=True)
    op.create_table('qualificacoes',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualificacoes_id'), 'qualificacoes', ['id'], unique=False)
    op.create_table('reserva_composta',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserva_composta_id'), 'reserva_composta', ['id'], unique=False)
    op.create_table('status_reserva',
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_status_reserva_id'), 'status_reserva', ['id'], unique=False)
    op.create_table('unidades_organizacionais',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidades_organizacionais_id'), 'unidades_organizacionais', ['id'], unique=False)
    op.create_table('ambientes',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=False),
    sa.Column('criticidade', sa.String(length=64), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('localizacao_id', sa.Integer(), nullable=False),
    sa.Column('horario_funcionamento', sa.String(length=255), nullable=False),
    sa.Column('requer_aprovacao', sa.Boolean(), nullable=False),
    sa.Column('buffer_antes_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('buffer_depois_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['localizacao_id'], ['localizacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambientes_id'), 'ambientes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('unidade_organizacional_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unidade_organizacional_id'], ['unidades_organizacionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('bloqueios_calendario',
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=False),
    sa.Column('prioridade', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloqueios_calendario_id'), 'bloqueios_calendario', ['id'], unique=False)
    op.create_table('manutencao_ambiente',
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencao_ambiente_id'), 'manutencao_ambiente', ['id'], unique=False)
    op.create_table('politica_reserva',
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('papel_id', sa.Integer(), nullable=False),
    sa.Column('antecedencia_min_horas', sa.Integer(), nullable=False),
    sa.Column('antecedencia_max_dias', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politica_reserva_id'), 'politica_reserva', ['id'], unique=False)
    op.create_table('qualificacoes_usuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('qualificacao_id', sa.Integer(), nullable=False),
    sa.Column('valido_ate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['qualificacao_id'], ['qualificacoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualificacoes_usuario_id'), 'qualificacoes_usuario', ['id'], unique=False)
    op.create_table('recursos',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=False),
    sa.Column('categoria', sa.String(length=64), server_default='GERAL', nullable=False),
    sa.Column('tipo_vinculo', sa.String(length=32), server_default='MOVEL', nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('localizacao_atual_id', sa.Integer(), nullable=True),
    sa.Column('ambiente_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['localizacao_atual_id'], ['localizacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recursos_id'), 'recursos', ['id'], unique=False)
    op.create_table('registros_auditoria',
    sa.Column('tipo_entidade', sa.String(length=128), nullable=False),
    sa.Column('id_alvo', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=64), nullable=False),
    sa.Column('realizado_por', sa.Integer(), nullable=False),
    sa.Column('realizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado_anterior', sa.String(length=4000), nullable=True),
    sa.Column('estado_posterior', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['realizado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_auditoria_id'), 'registros_auditoria', ['id'], unique=False)
    op.create_table('requisitos_ambiente',
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('qualificacao_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['qualificacao_id'], ['qualificacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisitos_ambiente_id'), 'requisitos_ambiente', ['id'], unique=False)
    op.create_table('reservas',
    sa.Column('reserva_mestre_id', sa.Integer(), nullable=True),
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('num_participantes', sa.Integer(), nullable=False),
    sa.Column('proposito', sa.String(length=128), nullable=False),
    sa.Column('checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('regra_recorrencia', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['reserva_mestre_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status_reserva.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    op.create_table('restricoes_ambiente',
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restricoes_ambiente_id'), 'restricoes_ambiente', ['id'], unique=False)
    op.create_table('usuario_papeis',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'papel_id', name='uq_usuario_papel')
    )
    op.create_index(op.f('ix_usuario_papeis_id'), 'usuario_papeis', ['id'], unique=False)
    op.create_table('aprovacoes',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('aprovador_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.String(length=64), server_default='INITIAL', nullable=False),
    sa.Column('data_decisao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comentarios', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aprovador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aprovacoes_id'), 'aprovacoes', ['id'], unique=False)
    op.create_table('buffer_execucao',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('hora_prevista_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_real_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('liberado_por', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.ForeignKeyConstraint(['liberado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buffer_execucao_id'), 'buffer_execucao', ['id'], unique=False)
    op.create_table('dependencias_reserva',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('depende_de_reserva_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depende_de_reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencias_reserva_id'), 'dependencias_reserva', ['id'], unique=False)
    op.create_table('disponibilidade_recurso',
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disponibilidade_recurso_id'), 'disponibilidade_recurso', ['id'], unique=False)
    op.create_table('emprestimos_recurso',
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('hora_retirada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_devolucao_prevista', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_devolucao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emprestimos_recurso_id'), 'emprestimos_recurso', ['id'], unique=False)
    op.create_table('escala_tecnico',
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escala_tecnico_id'), 'escala_tecnico', ['id'], unique=False)
    op.create_table('historico_status_reserva',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior_id', sa.Integer(), nullable=True),
    sa.Column('status_novo_id', sa.Integer(), nullable=False),
    sa.Column('data_mudanca', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['status_anterior_id'], ['status_reserva.id'], ),
    sa.ForeignKeyConstraint(['status_novo_id'], ['status_reserva.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_status_reserva_id'), 'historico_status_reserva', ['id'], unique=False)
    op.create_table('incidentes',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('severidade', sa.String(length=64), nullable=False),
    sa.Column('reportado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidentes_id'), 'incidentes', ['id'], unique=False)
    op.create_table('manutencao_recurso',
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencao_recurso_id'), 'manutencao_recurso', ['id'], unique=False)
    op.create_table('penalidades',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('duracao_dias', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aplicada_por', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aplicada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penalidades_id'), 'penalidades', ['id'], unique=False)
    op.create_table('recursos_reserva',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recursos_reserva_id'), 'recursos_reserva', ['id'], unique=False)
    op.create_table('reserva_composta_item',
    sa.Column('reserva_composta_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('critico', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_composta_id'], ['reserva_composta.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_composta_id', 'reserva_id', name='uq_reserva_composta_item')
    )
    op.create_index(op.f('ix_reserva_composta_item_id'), 'reserva_composta_item', ['id'], unique=False)
    op.create_table('suporte_reserva',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('tipo_suporte', sa.String(length=64), nullable=False),
    sa.Column('funcionario_responsavel_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_responsavel_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suporte_reserva_id'), 'suporte_reserva', ['id'], unique=False)
    op.create_table('versoes_reserva',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('alterado_por', sa.Integer(), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resumo_alteracao', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alterado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versoes_reserva_id'), 'versoes_reserva', ['id'], unique=False)
    op.create_table('apelos',
    sa.Column('penalidade_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('notas_resolucao', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['penalidade_id'], ['penalidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apelos_id'), 'apelos', ['id'], unique=False)
    op.drop_index(op.f('ix_resource_calendar_id'), table_name='resource_calendar')
    op.drop_table('resource_calendar')
    op.drop_index(op.f('ix_resource_checkouts_id'), table_name='resource_checkouts')
    op.drop_table('resource_checkouts')
    op.drop_index(op.f('ix_checkouts_id'), table_name='checkouts')
    op.drop_table('checkouts')
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_reservation_dependencies_id'), table_name='reservation_dependencies')
    op.drop_table('reservation_dependencies')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_appeals_id'), table_name='appeals')
    op.drop_table('appeals')
    op.drop_index(op.f('ix_reservation_support_id'), table_name='reservation_support')
    op.drop_table('reservation_support')
    op.drop_index(op.f('ix_environment_requirements_id'), table_name='environment_requirements')
    op.drop_table('environment_requirements')
    op.drop_index(op.f('ix_reservation_versions_id'), table_name='reservation_versions')
    op.drop_table('reservation_versions')
    op.drop_index(op.f('ix_calendar_blocks_id'), table_name='calendar_blocks')
    op.drop_table('calendar_blocks')
    op.drop_index(op.f('ix_penalties_id'), table_name='penalties')
    op.drop_table('penalties')
    op.drop_index(op.f('ix_reservation_resources_id'), table_name='reservation_resources')
    op.drop_table('reservation_resources')
    op.drop_index(op.f('ix_environment_resources_id'), table_name='environment_resources')
    op.drop_table('environment_resources')
    op.drop_index(op.f('ix_user_qualifications_id'), table_name='user_qualifications')
    op.drop_table('user_qualifications')
    op.drop_index(op.f('ix_environment_restrictions_id'), table_name='environment_restrictions')
    op.drop_table('environment_restrictions')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_environment_policies_id'), table_name='environment_policies')
    op.drop_table('environment_policies')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_environments_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_qualifications_id'), table_name='qualifications')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_organizational_units_id'), table_name='organizational_units')
    op.drop_table('organizational_units')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_policies',
    sa.Column('environment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_lead_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_lead_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buffer_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buffer_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requires_supervisor', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('environment_policies_environment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('environment_policies_pkey'))
    )
    op.create_index(op.f('ix_environment_policies_id'), 'environment_policies', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('user_roles_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_roles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_roles_pkey')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_role'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('environment_restrictions',
    sa.Column('environment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('environment_restrictions_environment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('environment_restrictions_pkey'))
    )
    op.create_index(op.f('ix_environment_restrictions_id'), 'environment_restrictions', ['id'], unique=False)
    op.create_table('user_qualifications',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qualification_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valid_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], name=op.f('user_qualifications_qualification_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_qualifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_qualifications_pkey'))
    )
    op.create_index(op.f('ix_user_qualifications_id'), 'user_qualifications', ['id'], unique=False)
    op.create_table('environment_resources',
    sa.Column('environment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_fixed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('environment_resources_environment_id_fkey')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('environment_resources_resource_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('environment_resources_pkey'))
    )
    op.create_index(op.f('ix_environment_resources_id'), 'environment_resources', ['id'], unique=False)
    op.create_table('reservations',
    sa.Column('parent_reservation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('environment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('responsible_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('participant_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('reservations_environment_id_fkey')),
    sa.ForeignKeyConstraint(['parent_reservation_id'], ['reservations.id'], name=op.f('reservations_parent_reservation_id_fkey')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('reservations_requester_id_fkey')),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], name=op.f('reservations_responsible_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reservations_pkey'))
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_table('reservation_resources',
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('reservation_resources_reservation_id_fkey')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('reservation_resources_resource_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reservation_resources_pkey'))
    )
    op.create_index(op.f('ix_reservation_resources_id'), 'reservation_resources', ['id'], unique=False)
    op.create_table('resources',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_mobile', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('current_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], name=op.f('resources_current_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resources_pkey'))
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_table('penalties',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('penalties_reservation_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('penalties_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('penalties_pkey'))
    )
    op.create_index(op.f('ix_penalties_id'), 'penalties', ['id'], unique=False)
    op.create_table('organizational_units',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('organizational_units_pkey'))
    )
    op.create_index(op.f('ix_organizational_units_id'), 'organizational_units', ['id'], unique=False)
    op.create_table('environments',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('criticality', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operating_hours', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requires_approval', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('environments_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('environments_pkey'))
    )
    op.create_index(op.f('ix_environments_id'), 'environments', ['id'], unique=False)
    op.create_table('qualifications',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('qualifications_pkey'))
    )
    op.create_index(op.f('ix_qualifications_id'), 'qualifications', ['id'], unique=False)
    op.create_table('calendar_blocks',
    sa.Column('environment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('calendar_blocks_environment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calendar_blocks_pkey'))
    )
    op.create_index(op.f('ix_calendar_blocks_id'), 'calendar_blocks', ['id'], unique=False)
    op.create_table('reservation_versions',
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('change_summary', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('reservation_versions_changed_by_fkey')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('reservation_versions_reservation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reservation_versions_pkey'))
    )
    op.create_index(op.f('ix_reservation_versions_id'), 'reservation_versions', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('campus', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('building', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('floor', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('locations_pkey'))
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('organizational_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['organizational_unit_id'], ['organizational_units.id'], name=op.f('users_organizational_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('environment_requirements',
    sa.Column('environment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qualification_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('environment_requirements_environment_id_fkey')),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], name=op.f('environment_requirements_qualification_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('environment_requirements_pkey'))
    )
    op.create_index(op.f('ix_environment_requirements_id'), 'environment_requirements', ['id'], unique=False)
    op.create_table('reservation_support',
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('support_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('assigned_staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], name=op.f('reservation_support_assigned_staff_id_fkey')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('reservation_support_reservation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reservation_support_pkey'))
    )
    op.create_index(op.f('ix_reservation_support_id'), 'reservation_support', ['id'], unique=False)
    op.create_table('appeals',
    sa.Column('penalty_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('resolution_notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['penalty_id'], ['penalties.id'], name=op.f('appeals_penalty_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appeals_pkey'))
    )
    op.create_index(op.f('ix_appeals_id'), 'appeals', ['id'], unique=False)
    op.create_table('approvals',
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('decision_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('approvals_approver_id_fkey')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('approvals_reservation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approvals_pkey'))
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey'))
    )
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=True)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('entity_type', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('performed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('before_state', sa.VARCHAR(length=4000), autoincrement=False, nullable=True),
    sa.Column('after_state', sa.VARCHAR(length=4000), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('audit_logs_performed_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('reported_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('incidents_reservation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incidents_pkey'))
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_table('reservation_dependencies',
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('depends_on_reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['depends_on_reservation_id'], ['reservations.id'], name=op.f('reservation_dependencies_depends_on_reservation_id_fkey')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('reservation_dependencies_reservation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reservation_dependencies_pkey'))
    )
    op.create_index(op.f('ix_reservation_dependencies_id'), 'reservation_dependencies', ['id'], unique=False)
    op.create_table('checkins',
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checkin_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('checkins_reservation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('checkins_pkey'))
    )
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    op.create_table('checkouts',
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checkout_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('checklist_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('checkouts_reservation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('checkouts_pkey'))
    )
    op.create_index(op.f('ix_checkouts_id'), 'checkouts', ['id'], unique=False)
    op.create_table('resource_checkouts',
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checkout_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('due_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('return_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('resource_checkouts_reservation_id_fkey')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('resource_checkouts_resource_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_checkouts_pkey'))
    )
    op.create_index(op.f('ix_resource_checkouts_id'), 'resource_checkouts', ['id'], unique=False)
    op.create_table('resource_calendar',
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('resource_calendar_resource_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_calendar_pkey'))
    )
    op.create_index(op.f('ix_resource_calendar_id'), 'resource_calendar', ['id'], unique=False)
    op.drop_index(op.f('ix_apelos_id'), table_name='apelos')
    op.drop_table('apelos')
    op.drop_index(op.f('ix_versoes_reserva_id'), table_name='versoes_reserva')
    op.drop_table('versoes_reserva')
    op.drop_index(op.f('ix_suporte_reserva_id'), table_name='suporte_reserva')
    op.drop_table('suporte_reserva')
    op.drop_index(op.f('ix_reserva_composta_item_id'), table_name='reserva_composta_item')
    op.drop_table('reserva_composta_item')
    op.drop_index(op.f('ix_recursos_reserva_id'), table_name='recursos_reserva')
    op.drop_table('recursos_reserva')
    op.drop_index(op.f('ix_penalidades_id'), table_name='penalidades')
    op.drop_table('penalidades')
    op.drop_index(op.f('ix_manutencao_recurso_id'), table_name='manutencao_recurso')
    op.drop_table('manutencao_recurso')
    op.drop_index(op.f('ix_incidentes_id'), table_name='incidentes')
    op.drop_table('incidentes')
    op.drop_index(op.f('ix_historico_status_reserva_id'), table_name='historico_status_reserva')
    op.drop_table('historico_status_reserva')
    op.drop_index(op.f('ix_escala_tecnico_id'), table_name='escala_tecnico')
    op.drop_table('escala_tecnico')
    op.drop_index(op.f('ix_emprestimos_recurso_id'), table_name='emprestimos_recurso')
    op.drop_table('emprestimos_recurso')
    op.drop_index(op.f('ix_disponibilidade_recurso_id'), table_name='disponibilidade_recurso')
    op.drop_table('disponibilidade_recurso')
    op.drop_index(op.f('ix_dependencias_reserva_id'), table_name='dependencias_reserva')
    op.drop_table('dependencias_reserva')
    op.drop_index(op.f('ix_buffer_execucao_id'), table_name='buffer_execucao')
    op.drop_table('buffer_execucao')
    op.drop_index(op.f('ix_aprovacoes_id'), table_name='aprovacoes')
    op.drop_table('aprovacoes')
    op.drop_index(op.f('ix_usuario_papeis_id'), table_name='usuario_papeis')
    op.drop_table('usuario_papeis')
    op.drop_index(op.f('ix_restricoes_ambiente_id'), table_name='restricoes_ambiente')
    op.drop_table('restricoes_ambiente')
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_requisitos_ambiente_id'), table_name='requisitos_ambiente')
    op.drop_table('requisitos_ambiente')
    op.drop_index(op.f('ix_registros_auditoria_id'), table_name='registros_auditoria')
    op.drop_table('registros_auditoria')
    op.drop_index(op.f('ix_recursos_id'), table_name='recursos')
    op.drop_table('recursos')
    op.drop_index(op.f('ix_qualificacoes_usuario_id'), table_name='qualificacoes_usuario')
    op.drop_table('qualificacoes_usuario')
    op.drop_index(op.f('ix_politica_reserva_id'), table_name='politica_reserva')
    op.drop_table('politica_reserva')
    op.drop_index(op.f('ix_manutencao_ambiente_id'), table_name='manutencao_ambiente')
    op.drop_table('manutencao_ambiente')
    op.drop_index(op.f('ix_bloqueios_calendario_id'), table_name='bloqueios_calendario')
    op.drop_table('bloqueios_calendario')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_ambientes_id'), table_name='ambientes')
    op.drop_table('ambientes')
    op.drop_index(op.f('ix_unidades_organizacionais_id'), table_name='unidades_organizacionais')
    op.drop_table('unidades_organizacionais')
    op.drop_index(op.f('ix_status_reserva_id'), table_name='status_reserva')
    op.drop_table('status_reserva')
    op.drop_index(op.f('ix_reserva_composta_id'), table_name='reserva_composta')
    op.drop_table('reserva_composta')
    op.drop_index(op.f('ix_qualificacoes_id'), table_name='qualificacoes')
    op.drop_table('qualificacoes')
    op.drop_index(op.f('ix_papeis_nome'), table_name='papeis')
    op.drop_index(op.f('ix_papeis_id'), table_name='papeis')
    op.drop_index(op.f('ix_papeis_codigo'), table_name='papeis')
    op.drop_table('papeis')
    op.drop_index(op.f('ix_localizacoes_id'), table_name='localizacoes')
    op.drop_table('localizacoes')
    # ### end Alembic commands ###
