"""ajustes

Revision ID: 89e39e5aaa73
Revises: 9cfd88748d73
Create Date: 2026-04-23 23:53:24.671597

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e39e5aaa73'
down_revision: str | Sequence[str] | None = '9cfd88748d73'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types that don't conflict with the status_reserva table name
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE status_aprovacao AS ENUM ('PENDENTE', 'APROVADO', 'REJEITADO');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE tipo_bloqueio_calendario AS ENUM ('MANUTENCAO', 'FERIADO', 'EVENTO', 'RESERVA_ADMIN');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE tipo_buffer AS ENUM ('PRE', 'POS');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE tipo_reserva AS ENUM ('SIMPLES', 'RECORRENTE', 'COMPOSTA');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE tipo_suporte AS ENUM ('TECNICO', 'LIMPEZA', 'SEGURANCA');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)

    # Drop FK constraints referencing status_reserva before dropping the table
    op.drop_constraint(op.f('historico_status_reserva_status_anterior_id_fkey'), 'historico_status_reserva', type_='foreignkey')
    op.drop_constraint(op.f('historico_status_reserva_status_novo_id_fkey'), 'historico_status_reserva', type_='foreignkey')
    op.drop_constraint(op.f('reservas_status_id_fkey'), 'reservas', type_='foreignkey')
    op.drop_index(op.f('ix_status_reserva_id'), table_name='status_reserva')
    op.drop_table('status_reserva')
    # Create status_reserva enum AFTER dropping the table of the same name,
    # otherwise PostgreSQL's implicit composite type for the table shadows it.
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE status_reserva AS ENUM ('RASCUNHO', 'AGUARDANDO_APROVACAO', 'APROVADA', 'REJEITADA', 'AGUARDANDO_CHECKIN', 'EM_USO', 'AGUARDANDO_CHECKOUT', 'CONCLUIDA', 'CANCELADA', 'NAO_COMPARECEU');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$
    """)
    op.alter_column('aprovacoes', 'status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='status_aprovacao', create_type=False),
               existing_nullable=False,
               postgresql_using='status::status_aprovacao')
    op.alter_column('bloqueios_calendario', 'tipo',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('MANUTENCAO', 'FERIADO', 'EVENTO', 'RESERVA_ADMIN', name='tipo_bloqueio_calendario', create_type=False),
               existing_nullable=False,
               postgresql_using='tipo::tipo_bloqueio_calendario')
    op.alter_column('buffer_execucao', 'tipo',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PRE', 'POS', name='tipo_buffer', create_type=False),
               existing_nullable=False,
               postgresql_using='tipo::tipo_buffer')
    op.add_column('historico_status_reserva', sa.Column('status_anterior', sa.Enum('RASCUNHO', 'AGUARDANDO_APROVACAO', 'APROVADA', 'REJEITADA', 'AGUARDANDO_CHECKIN', 'EM_USO', 'AGUARDANDO_CHECKOUT', 'CONCLUIDA', 'CANCELADA', 'NAO_COMPARECEU', name='status_reserva', create_type=False), nullable=True))
    op.add_column('historico_status_reserva', sa.Column('status_novo', sa.Enum('RASCUNHO', 'AGUARDANDO_APROVACAO', 'APROVADA', 'REJEITADA', 'AGUARDANDO_CHECKIN', 'EM_USO', 'AGUARDANDO_CHECKOUT', 'CONCLUIDA', 'CANCELADA', 'NAO_COMPARECEU', name='status_reserva', create_type=False), nullable=False))
    op.drop_column('historico_status_reserva', 'status_novo_id')
    op.drop_column('historico_status_reserva', 'status_anterior_id')
    op.add_column('reservas', sa.Column('status', sa.Enum('RASCUNHO', 'AGUARDANDO_APROVACAO', 'APROVADA', 'REJEITADA', 'AGUARDANDO_CHECKIN', 'EM_USO', 'AGUARDANDO_CHECKOUT', 'CONCLUIDA', 'CANCELADA', 'NAO_COMPARECEU', name='status_reserva', create_type=False), nullable=False))
    op.add_column('reservas', sa.Column('tipo', sa.Enum('SIMPLES', 'RECORRENTE', 'COMPOSTA', name='tipo_reserva', create_type=False), nullable=False))
    op.drop_column('reservas', 'status_id')
    op.alter_column('suporte_reserva', 'tipo_suporte',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('TECNICO', 'LIMPEZA', 'SEGURANCA', name='tipo_suporte', create_type=False),
               existing_nullable=False,
               postgresql_using='tipo_suporte::tipo_suporte')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert enum columns back to VARCHAR
    op.alter_column('suporte_reserva', 'tipo_suporte',
               existing_type=sa.Enum('TECNICO', 'LIMPEZA', 'SEGURANCA', name='tipo_suporte', create_type=False),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False,
               postgresql_using='tipo_suporte::varchar')
    op.alter_column('buffer_execucao', 'tipo',
               existing_type=sa.Enum('PRE', 'POS', name='tipo_buffer', create_type=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               postgresql_using='tipo::varchar')
    op.alter_column('bloqueios_calendario', 'tipo',
               existing_type=sa.Enum('MANUTENCAO', 'FERIADO', 'EVENTO', 'RESERVA_ADMIN', name='tipo_bloqueio_calendario', create_type=False),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False,
               postgresql_using='tipo::varchar')
    op.alter_column('aprovacoes', 'status',
               existing_type=sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='status_aprovacao', create_type=False),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False,
               postgresql_using='status::varchar')
    op.drop_column('historico_status_reserva', 'status_novo')
    op.drop_column('historico_status_reserva', 'status_anterior')
    op.drop_column('reservas', 'tipo')
    op.drop_column('reservas', 'status')
    # Drop enum types before recreating the status_reserva table
    op.execute("DROP TYPE IF EXISTS status_aprovacao")
    op.execute("DROP TYPE IF EXISTS tipo_bloqueio_calendario")
    op.execute("DROP TYPE IF EXISTS tipo_buffer")
    op.execute("DROP TYPE IF EXISTS status_reserva")
    op.execute("DROP TYPE IF EXISTS tipo_reserva")
    op.execute("DROP TYPE IF EXISTS tipo_suporte")
    # Recreate the status_reserva lookup table
    op.create_table('status_reserva',
    sa.Column('nome', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('status_reserva_pkey')),
    sa.UniqueConstraint('nome', name=op.f('status_reserva_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_status_reserva_id'), 'status_reserva', ['id'], unique=False)
    # Restore FK columns and constraints now that the table exists
    op.add_column('reservas', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('reservas_status_id_fkey'), 'reservas', 'status_reserva', ['status_id'], ['id'])
    op.add_column('historico_status_reserva', sa.Column('status_anterior_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('historico_status_reserva', sa.Column('status_novo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('historico_status_reserva_status_novo_id_fkey'), 'historico_status_reserva', 'status_reserva', ['status_novo_id'], ['id'])
    op.create_foreign_key(op.f('historico_status_reserva_status_anterior_id_fkey'), 'historico_status_reserva', 'status_reserva', ['status_anterior_id'], ['id'])
    # ### end Alembic commands ###
